# Generated by Django 3.0.4 on 2020-05-03 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200503_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='_list',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='api.List'),
            preserve_default=False,
        ),
    ]
