# Generated by Django 3.0.4 on 2020-05-06 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200503_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='_list',
            new_name='list_id',
        ),
    ]
