# Generated by Django 3.0.4 on 2020-05-06 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200507_0012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='list_id',
            new_name='listid',
        ),
    ]
