# Generated by Django 3.0.4 on 2020-05-06 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200507_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='listid',
            new_name='_list',
        ),
    ]
