# Generated by Django 3.0.4 on 2020-05-12 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200511_0848'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLists',
        ),
    ]
