# Generated by Django 3.0.4 on 2020-05-12 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200512_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='user',
            new_name='users',
        ),
    ]
